{{- if and .Values.adminsecret (eq .Values.operationMode "standard") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "aad-pod-identity.mic.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aad-pod-identity.labels" . | nindent 4 }}
    app.kubernetes.io/component: mic
data:
  Cloud: {{ required "A valid cloud environment name is required" .Values.adminsecret.cloud | b64enc | quote }}
  SubscriptionID: {{ required "A valid subscription id is required" .Values.adminsecret.subscriptionID | b64enc | quote }}
  ResourceGroup: {{ required "A valid resource group is required" .Values.adminsecret.resourceGroup | b64enc | quote }}
  VMType: {{ required "A valid vm type is required" .Values.adminsecret.vmType | b64enc | quote }}
  TenantID: {{ required "A valid cloud tenant id is required" .Values.adminsecret.tenantID | b64enc | quote }}
  ClientID: {{ required "A valid client id is required" .Values.adminsecret.clientID | b64enc | quote }}
  ClientSecret: {{ required "A valid client secret is required" .Values.adminsecret.clientSecret | b64enc | quote }}
  {{- if .Values.adminsecret.useMSI }}
  UseMSI: {{ .Values.adminsecret.useMSI | b64enc | quote }}
  UserAssignedMSIClientID: {{ .Values.adminsecret.userAssignedMSIClientID | b64enc | quote }}
  {{- end }}
{{- end }}
