[components.glade]

# Backport from Fedora rawhide: https://src.fedoraproject.org/rpms/glade/c/478c15c
# Required by meson's gnome.generate_gir; missing from f43 spec.
[[components.glade.overlays]]
description = "Add missing BuildRequires for gobject-introspection-devel needed by meson gnome.generate_gir"
type = "spec-add-tag"
tag = "BuildRequires"
value = "gobject-introspection-devel"
