[components.ghc-conduit-extra]

[components.ghc-conduit-extra.build]
check = { skip = true, skip_reason = "Tests fail due to lacking network access, and get stuck until they hit mock's 24 hour timeout." }
