version: '3'

services:
  jekyll:
    container_name: blog
    image: jekyll/jekyll:stable
    environment:
      - GEM_HOME=/usr/local/bundle
      - JEKYLL_ENV=development
    command: jekyll serve --future --watch --incremental
    ports:
      - 4000:4000
    volumes:
      - .:/srv/jekyll:cached
      - ./vendor/bundle:/usr/local/bundle:cached
