[components.coreutils]

[components.coreutils.build]
check = { skip = true, skip_reason = "Test tests/tail/inotify-rotate-resources.sh seems to fail due to environment issue and is blocking image build" }
