{{- if and .Values.rbac.enabled (eq .Values.operationMode "standard") }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "aad-pod-identity.mic.fullname" . }}
  labels:
    {{- include "aad-pod-identity.labels" . | nindent 4 }}
    app.kubernetes.io/component: mic
subjects:
- kind: ServiceAccount
  name: {{ template "aad-pod-identity.mic.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ template "aad-pod-identity.mic.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
