[images.vm-base]
description = "Base VM"
definition = { type = "kiwi", path = "vm-base/vm-base.kiwi" }

[images.container-base]
description = "Base Container"
definition = { type = "kiwi", path = "container-base/container-base.kiwi", profile = "Container-Base" }

[images.container-build]
description = "Build Container"
definition = { type = "kiwi", path = "container-base/container-base.kiwi", profile = "Container-Build" }
