# Default configuration overrides for Influxdb 2.0
# To see all available options, use the following command:
#    INFLUXD_CONFIG_PATH=/etc/influxdb/config.yaml influxd print-config

# No reporting by default
reporting-disable: true

#Enable token hashing
use-hashed-tokens: true

# Avoid OOM, adjust according to your HW specs
# By default it can easily exhaust RAM, so play it safe by default

# Reduce number of concurrently running queries
query-concurrency: 8
query-queue-size: 128
# Maximum memory for all queries - 512M
query-max-memory-bytes: 536870912
# Maximum memory per query - 64M
query-memory-bytes: 67108863

# Allow to move storage to different directory

bolt-path: /var/lib/influxdb/influxd.bolt
engine-path: /var/lib/influxdb/engine
nats-port: 4222
