#includes = ["**/*.comp.toml"]

#
# Components imported from Fedora
#

# provide small list of packages for development
[components.acl]
[components.argon2]
[components.at]
[components.attr]
[components.audit]
[components.authselect]
[components.azure-vm-utils]
[components.babel]
[components.bash-completion]
[components.bc]
[components.bind]
# skip binutils - ~60m+ duration
#[components.binutils]
# skip boost - ~21m duration
#[components.boost]
[components.brotli]
[components.btrfs-progs]
[components.bzip2]
[components.ca-certificates]
[components.checkpolicy]
[components.chkconfig]
[components.chrony]
[components.cloud-init]
[components.cloud-utils]
[components.coreutils]
[components.cpio]
[components.cracklib]
[components.cronie]
[components.crontabs]
[components.crypto-policies]
[components.cryptsetup]
# skip curl - ~60m+ duration
#[components.curl]
[components.cyrus-sasl]
[components.dbus]
[components.dbus-broker]
[components.dbus-python]
[components.device-mapper-persistent-data]
[components.dhcpcd]
[components.dialog]
[components.diffutils]
[components.ding-libs]
[components.dosfstools]
[components.dracut]
[components.dwz]
# skip dyninst - ~20m duration
#[components.dyninst]
# skip e2fsprogs - ~60m+ duration
#[components.e2fsprogs]
[components.ed]
[components.efi-rpm-macros]
[components.efivar]
[components.elfutils]
[components.ethtool]
[components.expat]
[components.file]
[components.filesystem]
[components.findutils]
[components.fmt]
[components.fonts-rpm-macros]
[components.forge-srpm-macros]
[components.fpc-srpm-macros]
[components.fstrm]
[components.fuse]
[components.gap-srpm-macros]
[components.gawk]
# skip gcc - ~60m+ duration
#[components.gcc]
[components.gdbm]
[components.gdisk]
# skip gettext - ~60m+ duration
#[components.gettext]
[components.ghc-srpm-macros]
# skip glib2 - ~20m duration
#[components.glib2]
# skip glibc - ~60m+ duration
#[components.glibc]
[components.gmp]
[components.gnat-srpm-macros]
[components.gnulib-l10n]
[components.gnupg2]
[components.gnutls]
[components.go-rpm-macros]
[components.gpgme]
[components.gpgverify]
[components.gpm]
[components.grep]
[components.groff]
[components.grub2]
[components.grubby]
[components.gssproxy]
[components.gzip]
[components.hiredis]
[components.hostname]
[components.hunspell]
[components.hunspell-en]
[components.hwdata]
[components.hyperv-daemons]
[components.inih]
[components.initscripts]
[components.iproute]
[components.iputils]
[components.irqbalance]
[components.jansson]
[components.jemalloc]
[components.jitterentropy]
[components.jq]
[components.json-c]
[components.kbd]
[components.kernel-srpm-macros]
[components.keyutils]
[components.kmod]
[components.krb5]
[components.less]
[components.libaio]
[components.libarchive]
[components.libassuan]
[components.libbpf]
[components.libbsd]
[components.libcap]
[components.libcap-ng]
[components.libcbor]
[components.libcomps]
[components.libconfig]
[components.libdnf]
[components.libeconf]
[components.libedit]
[components.libestr]
[components.libev]
[components.libevent]
[components.libfastjson]
# skip libffi - ~16m duration
#[components.libffi]
[components.libfido2]
[components.libgcrypt]
[components.libgpg-error]
[components.libidn2]
[components.libkcapi]
[components.libksba]
[components.libmaxminddb]
[components.libmd]
[components.libmnl]
[components.libmodulemd]
[components.libndp]
[components.libnetfilter_conntrack]
[components.libnfnetlink]
[components.libnftnl]
[components.libnl3]
[components.libnsl2]
[components.libpcap]
[components.libpipeline]
[components.libpsl]
[components.libpwquality]
[components.librepo]
[components.libreport]
[components.libretls]
[components.libselinux]
[components.libsemanage]
[components.libsepol]
[components.libsigsegv]
[components.libsolv]
[components.libssh]
[components.libstoragemgmt]
[components.libtasn1]
[components.libtirpc]
[components.libunistring]
[components.libusb1]
[components.libuser]
[components.libutempter]
[components.libuv]
[components.libverto]
[components.libxcrypt]
[components.libxml2]
[components.libyaml]
# skip linux-firmware - ~60m+ duration
#[components.linux-firmware]
[components.lmdb]
[components.lm_sensors]
[components.logrotate]
[components.lsof]
[components.lua]
[components.lua-rpm-macros]
[components.lvm2]
[components.lz4]
[components.lzo]
[components.man-db]
[components.man-pages]
[components.mdadm]
[components.microcode_ctl]
[components.mokutil]
[components.mpdecimal]
[components.mpfr]
[components.nano]
[components.ncurses]
[components.netcat]
[components.nettle]
[components.net-tools]
# skip NetworkManager - ~15m duration
#[components.NetworkManager]
[components.newt]
[components.nfs-utils]
[components.nftables]
[components.nghttp2]
[components.npth]
# skip nss - ~60m+ duration
#[components.nss]
[components.numactl]
[components.ocaml-srpm-macros]
[components.oniguruma]
[components.openblas-srpm-macros]
[components.openldap]
# skip openssh - ~60m+ duration
#[components.openssh]
# skip openssl - ~60m+ duration
#[components.openssl]
[components.openssl-pkcs11]
