#includes = ["**/*.comp.toml"]

#
# Components imported from Fedora
#

# About 30 packages

[components.acl]
[components.apache-sshd]
[components.cdparanoia]
[components.dosfstools]
[components.dracut]
[components.file]
[components.filesystem]
[components.gcr]
[components.ghc-data-default-class]
[components.ghc-pretty-show]
#[components.golang-github-evanphx-json-patch]
[components.gdisk]
[components.gmp]
[components.kf6-knotifications]
[components.mingw-vulkan-headers]
[components.mtdev]
[components.maven-invoker]
#[components.jakarta-inject1.0]
[components.mokutil]
[components.dav1d]
[components.chkconfig]
[components.dbus-glib]
[components.ghc-HUnit]
#[components.golang-github-creack-pty]
[components.docbook5-schemas]
[components.dom4j]
[components.easymock]
[components.mingw-dlfcn]
[components.ghc-tasty-quickcheck]
[components.golang-github-google-cel]
[components.gssproxy]
[components.docbook-style-dsssl]
[components.geocode-glib]
[components.ghc-serialise]
[components.ocaml-cairo]
[components.autoconf]
[components.cups-filters]


