#includes = ["**/*.comp.toml", "components-full.toml"]

#
# Components imported from Fedora with no per-component modifications.
# Please keep this list sorted alphabetically for readability.
#

[components.acl]
[components.dosfstools]
[components.dracut]
[components.file]
[components.filesystem]
[components.gdisk]
[components.gmp]
