#
# Components imported from Fedora with no per-component modifications.
# Please keep this list sorted alphabetically for readability.
#

[components.acl]
[components.argon2]
[components.at]
[components.attr]
[components.audit]
[components.authselect]
[components.azure-vm-utils]
[components.babel]
[components.bash-completion]
[components.bc]
[components.bind]
[components.binutils]
[components.boost]
[components.brotli]
[components.btrfs-progs]
[components.bzip2]
