#includes = ["**/*.comp.toml"]

#
# Components imported from Fedora
#

# provide small list of packages for development

[components.acl]
[components.dosfstools]
[components.file]
[components.filesystem]
