includes = ["**/*.comp.toml", "components-full.toml"]

#
# Components imported from Fedora with no per-component modifications.
# Please keep this list sorted alphabetically for readability.
#

[components.acl]
[components.argon2]
[components.at]
[components.attr]
[components.audit]
[components.authselect]
[components.azure-vm-utils]
[components.babel]
[components.bash-completion]
[components.bc]
[components.bind]
[components.binutils]
[components.boost]
[components.brotli]
[components.btrfs-progs]
[components.bzip2]
[components.ca-certificates]
[components.checkpolicy]
[components.chkconfig]
[components.chrony]
[components.cloud-init]
[components.cloud-utils]
[components.cpio]
[components.cracklib]
[components.cronie]
[components.crontabs]
[components.crypto-policies]
[components.cryptsetup]
[components.curl]
[components.cyrus-sasl]
[components.dbus]
[components.dbus-broker]
[components.dbus-python]
[components.device-mapper-persistent-data]
[components.dhcpcd]
[components.dialog]
[components.diffutils]
[components.ding-libs]
[components.dosfstools]
[components.dracut]
[components.dwz]
[components.dyninst]
[components.e2fsprogs]
[components.ed]
[components.efi-rpm-macros]
[components.efivar]
[components.elfutils]
[components.ethtool]
[components.expat]
[components.file]
[components.filesystem]
[components.findutils]
[components.fmt]
[components.fonts-rpm-macros]
[components.forge-srpm-macros]
[components.fpc-srpm-macros]
[components.fstrm]
[components.fuse]
[components.gap-srpm-macros]
[components.gawk]
[components.gcc]
[components.gdbm]
[components.gdisk]
[components.gettext]
[components.ghc-srpm-macros]
[components.glib2]
[components.glibc]
[components.gmp]
[components.gnat-srpm-macros]
[components.gnulib-l10n]
[components.gnupg2]
[components.gnutls]
[components.go-rpm-macros]
[components.gpgme]
[components.gpgverify]
[components.gpm]
[components.grep]
[components.groff]
[components.grub2]
[components.grubby]
[components.gssproxy]
[components.gzip]
[components.hiredis]
[components.hostname]
[components.hunspell]
[components.hunspell-en]
[components.hwdata]
[components.hyperv-daemons]
[components.inih]
[components.initscripts]
[components.iproute]
[components.iputils]
[components.irqbalance]
[components.jansson]
[components.jemalloc]
[components.jitterentropy]
[components.jq]
[components.json-c]
[components.kbd]
[components.kernel-srpm-macros]
[components.keyutils]
[components.kiwi]
[components.kmod]
[components.krb5]
[components.less]
[components.libaio]
[components.libarchive]
[components.libassuan]
[components.libbpf]
[components.libbsd]
[components.libcap]
[components.libcap-ng]
[components.libcbor]
[components.libcomps]
[components.libconfig]
[components.libdnf]
[components.libeconf]
[components.libedit]
[components.libestr]
[components.libev]
[components.libevent]
[components.libfastjson]
[components.libffi]
[components.libfido2]
[components.libgcrypt]
[components.libgpg-error]
[components.libidn2]
[components.libkcapi]
[components.libksba]
[components.libmaxminddb]
[components.libmd]
[components.libmnl]
[components.libmodulemd]
[components.libndp]
[components.libnetfilter_conntrack]
[components.libnfnetlink]
[components.libnftnl]
[components.libnl3]
[components.libnsl2]
[components.libpcap]
[components.libpipeline]
[components.libpsl]
[components.libpwquality]
[components.librepo]
[components.libreport]
[components.libretls]
[components.libselinux]
[components.libsemanage]
[components.libsepol]
[components.libsigsegv]
[components.libsolv]
[components.libssh]
[components.libstoragemgmt]
[components.libtasn1]
[components.libtirpc]
[components.libunistring]
[components.libusb1]
[components.libuser]
[components.libutempter]
[components.libuv]
[components.libverto]
[components.libxcrypt]
[components.libxml2]
[components.libyaml]
[components.linux-firmware]
[components.lmdb]
[components.lm_sensors]
[components.logrotate]
[components.lsof]
[components.lua]
[components.lua-rpm-macros]
[components.lvm2]
[components.lz4]
[components.lzo]
[components.man-db]
[components.man-pages]
[components.mdadm]
[components.microcode_ctl]
[components.mokutil]
[components.mpdecimal]
[components.mpfr]
[components.nano]
[components.ncurses]
[components.netcat]
[components.nettle]
[components.net-tools]
[components.NetworkManager]
[components.newt]
[components.nfs-utils]
[components.nftables]
[components.nghttp2]
[components.npth]
[components.nss]
[components.numactl]
[components.ocaml-srpm-macros]
[components.oniguruma]
[components.openblas-srpm-macros]
[components.openldap]
[components.openssh]
[components.openssl]
[components.openssl-pkcs11]
[components.os-prober]
[components.p11-kit]
[components.package-notes]
[components.pam]
[components.parted]
[components.pciutils]
[components.pcre2]
[components.perl-Carp]
[components.perl-constant]
[components.perl-Encode]
[components.perl-Exporter]
[components.perl-File-Path]
[components.perl-File-Temp]
[components.perl-Getopt-Long]
[components.perl-HTTP-Tiny]
[components.perl-MIME-Base64]
[components.perl-parent]
[components.perl-PathTools]
[components.perl-Pod-Escapes]
[components.perl-podlators]
[components.perl-Pod-Perldoc]
[components.perl-Pod-Simple]
[components.perl-Pod-Usage]
[components.perl-Scalar-List-Utils]
[components.perl-Socket]
[components.perl-srpm-macros]
[components.perl-Storable]
[components.perl-Term-ANSIColor]
[components.perl-Term-Cap]
[components.perl-Text-ParseWords]
[components.'perl-Text-Tabs+Wrap']
[components.perl-Time-Local]
[components.pkgconf]
[components.policycoreutils]
[components.popt]
[components.procps-ng]
[components.protobuf-c]
[components.psacct]
[components.psmisc]
[components.publicsuffix-list]
[components.pv]
[components.pyserial]
[components.'python3.14']
[components.python-attrs]
[components.python-awscrt]
[components.python-cffi]
[components.python-chardet]
[components.python-colorama]
[components.python-configobj]
[components.python-cryptography]
[components.python-dateutil]
[components.python-distro]
[components.python-docutils]
[components.python-idna]
[components.python-jinja2]
[components.python-jmespath]
[components.python-jsonpatch]
[components.python-jsonpointer]
[components.python-jsonschema]
[components.python-markupsafe]
[components.python-netifaces]
[components.python-oauthlib]
[components.python-pip]
[components.python-ply]
[components.python-prettytable]
[components.python-prompt-toolkit]
[components.python-pycparser]
[components.python-pyrsistent]
[components.python-pysocks]
[components.python-requests]
[components.python-rpm-macros]
[components.python-ruamel-yaml]
[components.python-ruamel-yaml-clib]
[components.python-setuptools]
[components.python-six]
[components.python-systemd]
[components.python-urllib3]
[components.python-wcwidth]
[components.pytz]
[components.PyYAML]
[components.quota]
[components.rdma-core]
[components.readline]
[components.rng-tools]
[components.rootfiles]
[components.rpcbind]
[components.rsync]
[components.rsyslog]
[components.rust]
[components.sbsigntools]
[components.screen]
[components.sdbus-cpp]
[components.sed]
[components.selinux-policy]
[components.setools]
[components.setup]
[components.shadow-utils]
[components.shim]
[components.slang]
[components.sqlite]
[components.sssd]
[components.strace]
[components.sudo]
[components.sysstat]
[components.systemd]
[components.systemtap]
[components.tar]
[components.tbb]
[components.tcpdump]
[components.tcsh]
[components.texinfo]
[components.time]
[components.tpm2-tss]
[components.traceroute]
[components.tree-sitter-srpm-macros]
[components.tzdata]
[components.unzip]
[components.userspace-rcu]
[components.util-linux]
[components.vim]
[components.WALinuxAgent]
[components.which]
[components.words]
[components.xfsdump]
[components.xfsprogs]
[components.xxhash]
[components.xz]
[components.zchunk]
[components.zig-srpm-macros]
[components.zip]
[components.zlib-ng]
[components.zstd]
