#includes = ["**/*.comp.toml"]

#
# Components imported from Fedora
#

# provide small list of packages for development

[components.acl]

[components.diffutils]
[components.dosfstools]
[components.dracut]
[components.dwz]
[components.ed]
[components.elfutils]
[components.file]
[components.filesystem]
[components.findutils]
[components.gawk]
[components.gcc14]
[components.gdisk]
[components.gettext]
[components.glibc]
[components.gmp]
[components.gpgme]
[components.grep]
[components.gzip]
