language: go
sudo: required
dist: trusty

go:
  - 1.11.x
  - 1.12.x

env:
  global:
  - PATH=$GOROOT/bin:$GOPATH/bin:$PATH
  - CGO_ENABLED=0
  matrix:
  - TARGET=386
  - TARGET=amd64
  - TARGET=arm
  - TARGET=arm64
  - TARGET=ppc64le
  - TARGET=s390x

matrix:
  fast_finish: true
  include:
    - os: windows
      env: TARGET=amd64
      go: 1.11.x
    - os: windows
      env: TARGET=amd64
      go: 1.12.x

install:
  - go get github.com/onsi/ginkgo/ginkgo
  - go get github.com/containernetworking/cni/cnitool
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/modocache/gover
  - go get github.com/mattn/goveralls

script:
 - |
   if [ "${TARGET}" == "amd64" ]; then
     GOARCH="${TARGET}" ./test_${TRAVIS_OS_NAME}.sh
   else
     GOARCH="${TARGET}" ./build_linux.sh
   fi

notifications:
  email: false

git:
  depth: 9999999
